artifactory:
  ce: https://ci-artifactory.corda.r3cev.com/artifactory/corda-enterprise/com/r3/corda
packages:
  - name: corda
    repo_type: CE
    alias:
      - corda
      - ce corda
    link: https://ci-artifactory.corda.r3cev.com/artifactory/corda-enterprise/com/r3/corda/corda/{version}/corda-{version}.jar
  - name: database-manager
    repo_type: CE
    alias:
      - database-manager
      - tools-database-manager
      - dbmtool
    link: https://ci-artifactory.corda.r3cev.com/artifactory/corda-enterprise/com/r3/corda/tools-database-manager/{version}/tools-database-manager-{version}.jar
